### ISSUE TITLE
Handle Content Types

### ISSUE THREAD

**Issue by chrisduerr** [quininer/x11-clipboard#13]
Using x11-clipboard through the clipboard-rust crate, it seems like content types lead to timeouts whenever trying to paste something.

This has been reported to Alacritty in https://github.com/jwilm/alacritty/issues/2595.

I'd expect that when the content type is set to text/plain, everything should work the same way it does when no content type is set. Currently this operation times out.

If an image is loaded, I'd expect it to fail, however I'd expect it to fail instantly. Currently the operation also times out.

**Comment by quininer** [comment]
Currently all non-target types are ignored, and it seems that throwing an error is the right thing to do. As for text/plain, we need to set multiple targets, which requires changing some APIs.

I will try to fix it later.

**Comment by chrisduerr** [comment]
Thanks! Just to clarify, I personally don't care about non-text content types at all, since Alacritty won't ever have to handle them as far as I'm concerned. However, even then a quick error is obviously preferable over a long blocking timeout.

**Comment by quininer** [comment]
@chrisduerr Can you try to see if this commit https://github.com/quininer/x11-clipboard/commit/0746c0e56e3ff239bbf7bdd7441f2dcca40e4f8d is valid?

**Comment by chrisduerr** [comment]
I can't reproduce any blocking issues anymore, so seems to be working great!

Supporting explicitly set text content types would be the only remaining issue, however that's far less of a priority for me personally. So if that's gonna take a while and require API changes, a non-breaking fix release might be reasonable first.

**Comment by quininer** [comment]
0.3.3 has been released!

I will close this issue now and `multiple target support ` will trace in https://github.com/quininer/x11-clipboard/issues/7. I don't remember why I didn't implement it immediately. If I have time, I will look at it again.
