### ISSUE TITLE
Monitor contents of PRIMARY selection: provide example

### ISSUE THREAD

**Issue by ngirard** [quininer/x11-clipboard#14]
Hi,
Could I use your crate to monitor the contents of the PRIMARY selection ?

**Comment by quininer** [comment]
Yes, you can refer to [this code](https://github.com/farseerfc/ydcv-rs/blob/master/src/main.rs#L143).

**Comment by ngirard** [comment]
Aww nice, thanks ! Let me just come up with a sample code I'll submit as a PR.
