### ISSUE TITLE
Zombie cat processes when loading clipboard

### ISSUE THREAD

**Issue by dnut** [quininer/x11-clipboard#24]
Every time I call Clipboard::load, if there is anything in the clipboard, I am left with a zombie process of `cat`. Also, once after polling for a while I saw an error for too many clients (haven't been able to reproduce this error though). Is xcb using cat under the hood somehow? I'm seeing this behavior when access the clipboard in mutter. Mutter is a wayland compositor but it works as an x11 clipboard.

**Comment by quininer** [comment]
I have not been able to reproduce this issue, test in kde wayland + chromium x11 + alacritty x11.

This crate doesn't call `cat` directly anyway, you may need to look elsewhere for answers. It could be in xcb, it could be in wayland compositor, it could be in the x11 client where the content is pasted.

**Comment by dnut** [comment]
Sorry I got mixed up about which function in my code was causing this error. I tracked it down to another library.

https://github.com/YaLTeR/wl-clipboard-rs/pull/26
