### ISSUE TITLE
Update xcb

### ISSUE THREAD

**Issue by piegamesde** [quininer/x11-clipboard#25]
See https://github.com/RustSec/advisory-db/issues/653. Since xcb is apparently unmaintained and the issue has been fixed, the issue suggests migrating to `x11rb` instead. I also found https://github.com/rust-x-bindings/rust-xcb/issues/107

**Comment by rtbo** [comment]
Hi, I am (back) maintaining `rust-xcb`. 
`v1.0.0` has been released. All the soundness issues are now resolved.

**Comment by Zageron** [comment]
Dependabot is yelling about this repositories use of xcb in 0.6.1.
I see you've resolved the issues, but didn't release a new version.
Any blockers?
