### ISSUE TITLE
Primary clipboard and clipboard lag for initial window

### ISSUE THREAD

**Issue by kchibisov** [quininer/x11-clipboard#42]
It seems like bump for `x11_clipboard` from `0.7.0` to `0.8.1` introduced this https://github.com/alacritty/alacritty/issues/7501 and probably also this https://github.com/alacritty/alacritty/issues/7500 since the only change we made to clipboard is to do the said bump.

Which was intended to solve this https://github.com/alacritty/alacritty/issues/3601 .

**Comment by awused** [comment]
It would be very strange for https://github.com/quininer/x11-clipboard/pull/39 to have caused this, since that one only discards stale messages from the X server and shouldn't cause new instances of stale values being read.
