### ISSUE TITLE
Can't paste selection into vim

### ISSUE THREAD

**Issue by chetgurevitch** [quininer/x11-clipboard#8]
ref https://github.com/jwilm/alacritty/pull/522

**Comment by quininer** [comment]
Can you reproduce it on 0.2.2?

**Comment by chetgurevitch** [comment]
Actually I'm not sure this is an issue in x11-clipboard on second thought. Turns out "*p stopped working in neovim b/c xclip was its clipboard provider and I'd uninstalled it. Alacritty's builtin ctrl+shift+v functions just fine and "*p works properly again after reinstalling xclip (or another provider like xsel).

@jwilm can you still reproduce this after doing a cargo update and rebuilding the clipboard branch? Also were you using neovim or regular vim? "*p doesn't work out of the box for me in regular vim from the arch repos, regardless of terminal.

**Comment by quininer** [comment]
I think it has long been [fixed](https://github.com/quininer/x11-clipboard/issues/6#event-1310414834). If not, you can reopen it.
